### ISSUE TITLE
`collectionViewLayout.minimumInteritemSpacing` is not respected

### ISSUE THREAD

**Issue by eimantas** [schibsted/layout#10]
Version: 0.48
Xcode: 9b5
iOS Sim: 11.0

The `collectionViewLayout.minimumInteritemSpacing` attribute in the `<UICollectionView>` tag is not respected through fixed value or constant.

**Comment by nicklockwood** [comment]
This seems to be working in the SampleApp. Can you provide some XML that demonstrates the problem?

**Comment by eimantas** [comment]
This is the minimum xml that reproduces the problem:

```xml
<UIView
    width="100%"
    height="100%"
    top="0"
    left="0">
    <UITableView
        width="parent.width"
        height="parent.height"
        top="parent.top"
        left="parent.left"
        backgroundColor="#fff"
        rowHeight="116">
        <UIView
            height="326">

            <UICollectionView
                top="71"
                width="parent.width"
                height="255"
                outlet="bannerCollectionView"
                backgroundColor="#fff"
                isPagingEnabled="true"
                collectionViewLayout.sectionInset.left="10"
                collectionViewLayout.sectionInset.right="10"
                collectionViewLayout.minimumInteritemSpacing="100"
                collectionViewLayout.scrollDirection="horizontal"
                collectionViewLayout.estimatedItemSize.width="0"
                collectionViewLayout.estimatedItemSize.height="0"
                collectionViewLayout.itemSize.width="90%"
                collectionViewLayout.itemSize.height="200">
                <UICollectionViewCell
                    reuseIdentifier="Cell"
                    backgroundColor="#f00">

                    <UILabel
                    width="100%"
                    left="0"
                    top="(parent.height - height) / 2"
                    text="Foo" />
                </UICollectionViewCell>
            </UICollectionView>
        </UIView>
    </UITableView>
</UIView>
```

**Comment by nicklockwood** [comment]
OK, I'm not much of an expert on UICollectionView, but this doesn't seem to be a Layout-specific problem, as a StackOverflow search reveals a lot of people with similar issues.

Using ` collectionViewLayout.minimumLineSpacing` instead of ` collectionViewLayout.minimumInteritemSpacing` seems to have the desired effect.

    collectionViewLayout.minimumLineSpacing="100"

**Comment by eimantas** [comment]
If i hadn't read the documentation, I wouldn't say it makes sense. Then again, after reading it - it still doesn't make sense to me:

> For a __vertically__ scrolling grid, this value represents the minimum spacing __between items in the same row__. For a __horizontally__ scrolling grid, this value represents the minimum __spacing between items in the same column__.

Emphasis mine.
