### ISSUE TITLE
[Question] Using Layout with RxCocoa

### ISSUE THREAD

**Issue by rachelfong** [schibsted/layout#110]
I am currently creating a project in Swift which heavily relies on RxSwift and RxCocoa. Are there some basic tutorials in place for binding using RxCocoa?

**Comment by nicklockwood** [comment]
@rachelfong I'm afraid I don't have any experience with RxSwift/Cocoa, and there's no support for them built into Layout, but if bindings can work with ordinary IBOutlets then you should be able to use them with Layout in the same way you would with a Storyboard.

**Comment by mariob** [comment]
@rachelfong, I've wrote a post about this topic a while ago on medium. It shows how you can create an Reactive extension which returns a Binder for state variables, if that's the preferred way for you to go. Else you could just use outlets as suggested by @nicklockwood. Works exactly the same as you'd expect from storybords.

https://medium.com/@marioboikov/rxswift-and-layout-aaf0ffce90e6

If you want to enjoy hot reloading of the views you need to do the Rx bindings after the layout node has been created, preferable in

`func layoutDidLoad(_ layoutNode: LayoutNode)`

**Comment by rachel-13** [comment]
Thank you for the blogspot. It was very helpful. Closing this issue for now.
