### ISSUE TITLE
Global/Default xml constants

### ISSUE THREAD

**Issue by viniciussoares** [schibsted/layout#119]
My current project is an universal app and most of my xml require some tweaks depending on the device type (iphone/ipad) and size (width and height). Usually is simple things, like font size or view height.

It would be cool to be able to define global constants or have a defined set of constants like `ipad`, `iphone`, `deviceWidth`, `deviceHeight`:

```
<UILabel font="{ipad ? '24 semibold' ; '18 semibold'}" />

// or 

<UIView height="{deviceHeight * 0.2}" />
```

There's a way to do this today? What you guys think about it?

I feel like i'm repeating the same constants throughout my XMLs over and over again.

**Comment by nicklockwood** [comment]
@viniciussoares there's no way to specify global constants currently, but if you create a global dictionary of these constants then you can pass it into the contructor of every LayoutNode quite easily without doing anything in the XML:

```swift
extension UIDevice {
    static let layoutConstants: [String: Any] = [
        "ipad": UIDevice.current.userInterfaceIdiom == .pad,
        "iphone": UIDevice.current.userInterfaceIdiom == .phone,
        "deviceWidth": UIScreen.main.bounds.width,
        "deviceHeight": UIScreen.main.bounds.height,
    ]
}

....

self.loadLayout("foo.xml", constants: UIDevice.layoutConstants, otherConstants, ....)
```

Alternatively, if you have device-specific fonts or colors you can define these as static methods of UIFont and then use them directly in your XML:

```swift
extension UIFont {
    @objc static var myFont: UIFont {
        return UIDevice.current.userInterfaceIdiom == .pad ?
            .systemFont(ofSize: 24) : .systemFont(ofSize: 18)
    }
}
```

```xml
<UILabel font="{UIFont.myFont} semibold" />
```

**Comment by viniciussoares** [comment]
Make sense, thanks @nicklockwood 🎉
