### ISSUE TITLE
Setting custom property value once initialised 

### ISSUE THREAD

**Issue by silentninja** [schibsted/layout#128]
Is there a way to set custom property value once the view size is initialised. I want to know the size of the view before setting the value, using frame.size.height returns zero since the frame is initialised with zero

**Comment by nicklockwood** [comment]
There’s currently no way to control this, but the property will be set again once the frame size is set so a (possibly ugly) workaround would be to override the setter for the property and ignore the value if the frame size is currently zero.

**Comment by silentninja** [comment]
I am doing the exact same thing, looks hacky but gets the job done!
