### ISSUE TITLE
Could not cast value of type '__NSCFNumber' (0x10cc8c2d8) to '__C.NSLineBreakMode' (0x102ac8818)

### ISSUE THREAD

**Issue by ardramli** [schibsted/layout#129]
I'm getting this error: 
`Could not cast value of type '__NSCFNumber' (0x10cc8c2d8) to '__C.NSLineBreakMode' (0x102ac8818)`

in LayoutExpression.swift line 749.
It's working fine on the Simulator, but when I run on actual device, my app crashed and gave me this error. 

I'm not sure what I did wrong but it only happens on one ViewController. While others works just fine.

**Comment by nicklockwood** [comment]
If you could submit a sample project that demonstrates the problem, I’ll try to track it down.

**Comment by ardramli** [comment]
I figured out what causes the crash. It's when I'm trying to set a constant for attributedTitle for a UIButton. Then, I create an outlet of the UIButton and used `myButtonsetAttributedTitle(attributedString, for: .normal)` it's no longer crashing. Maybe you can fix it.

**Comment by nicklockwood** [comment]
@ardramli this is now fixed on the develop branch.

**Comment by nicklockwood** [comment]
Fixed in version 0.6.25
