### ISSUE TITLE
Swift 4.2 / XCode 10 compatiblity

### ISSUE THREAD

**Issue by Kaspik** [schibsted/layout#130]
Hey team!

Currently Layout is the only pod inside our huge app that is not working on XCode 10 beta. I'm not opening this as issue that should be addressed ASAP to release, but to start conversation and migration to this version at least on some branch or master.

Here are things that are not working:
`AnyExpression.swift`
- `'ImplicitlyUnwrappedOptional' has been renamed to 'Optional'`
<img width="1614" alt="screenshot 2018-06-05 at 16 16 18" src="https://user-images.githubusercontent.com/7204168/41007768-3c230238-68dc-11e8-806d-20eaa2a4d54b.png">

- `Conflicting conformance of 'ClosedRange<Bound>' to protocol '_Range'; there cannot be more than one conformance, even with different conditional bounds`
<img width="1639" alt="screenshot 2018-06-05 at 16 20 46" src="https://user-images.githubusercontent.com/7204168/41007801-6f0505e8-68dc-11e8-8c41-9b1f28d464ff.png">
These are there multiple-times actually.

Let me know what you are planning about these updates, if we should create branch, or just PRs, or if you are going to take care of that. Thank you!

**Comment by nicklockwood** [comment]
@Kaspik I’ve already completed most of the fixes. Should have a 4.2-compatible release ready shortly.

**Comment by nicklockwood** [comment]
@Kaspik OK, I've pushed a version that supports 4.1.5 to the develop branch (4.1.5 is what Xcode 10 beta uses when you select "Swift 4" as the language version, and it's probably what you're using based on the errors you reported).

Full Swift 4.2 support will take a little bit longer as Apple has renamed a load of UIKit methods and constants.

**Comment by Kaspik** [comment]
Ohh perfect, yeah, I don’t need 4.2 probably if 4.1.5 is what XCode 10 uses. I’ll try the branch. Thank you!

**Comment by Kaspik** [comment]
@nicklockwood Perfect, develop works a so the app, thank you!

**Comment by nicklockwood** [comment]
Fixed in version 0.6.25
