### ISSUE TITLE
The target “Layout” contains source code developed with Swift 2.x

### ISSUE THREAD

**Issue by aledalgrande** [schibsted/layout#132]
When I create a new project and install the pod version 0.6.27, open Xcode 9.4.1 I get:
```
The target “Layout” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.
```

Is it because I created an Obj-C project?

**Comment by nicklockwood** [comment]
I think it may be because the .swift-version file in the Layout repo is still set to 3.1, which I should probably update.

If you manually set the Swift version in the Pods > Layout target, it should solve that (although I'm getting a bunch of errors when I try it that may or may not be related)

**Comment by nicklockwood** [comment]
FYI, you can use this solution in your Podfile to avoid having to set the swift version manually every time you run `pod install/update`: https://stackoverflow.com/questions/40501440/how-to-set-the-legacy-swift-version-for-each-pod-in-podfile-xcode-9-0-swift-3-2

**Comment by aledalgrande** [comment]
yeah setting to 4.0 worked
