### ISSUE TITLE
UIVisualEffectView support

### ISSUE THREAD

**Issue by algrid** [schibsted/layout#134]
Hey, thanks for a great framework!

I have a question/feature request.

As I can see currently one can't use `UIVisualEffectView` in layout. If I add it with some subviews I get a runtime crash saying that subviews shouldn't be added directly, instead one should add them to  `UIVisualEffectView`'s `contentView`.

It'd would be nice to support this automatically and also allow to set a visual effect like `UIBlurEffect ` in that view definition.

**Comment by nicklockwood** [comment]
@algrid thanks for reporting this - I'll try to get it fixed asap.

**Comment by nicklockwood** [comment]
@algrid this is fixed in 0.6.28.

**Comment by algrid** [comment]
@nicklockwood it works great, thank you!
