### ISSUE TITLE
How best to use UITextField 

### ISSUE THREAD

**Issue by den2k** [schibsted/layout#136]
I'm pretty new to Layout and need some help.  I'm using loadLayout to create a login page, but I am wondering how I bring the values that a users enters back to the LoginScreen view controller?  I did not find specific examples of text inputs for this framework. Should I add an IBOUTLET in the view controller? Do I need to include a STATE or CONSTANTS in self.loadLayout?  Any suggestion would be helpful in saving a ton of trial and error. Thanks.

```
class LoginScreen: UIViewController, LayoutLoading, UITextFieldDelegate
{
    override func viewDidLoad()
    {
        super.viewDidLoad()        
        self.loadLayout(
            named: "LoginScreen.xml",
            state: [
                 ...something?...
            ]
        )
    }
}
```
LoginScreen.xml
```
    <!-- user name / email -->
    <UITextField
        placeholder="user name / email"
        top="previous.bottom + 30"
        left="50% - width/2"
        width="100% - 40"
        height="45"
        layer.cornerRadius="5"
        textAlignment="center"
    />
```

**Comment by nicklockwood** [comment]
Yes, you should use an IBOutlet to get the value out of the text field. Add the outlet to your view controller and then reference it in your UITextField xml using `outlet=“foo”` where foo is the name of the outlet variable.

If you need to set the value in the field (e.g. to pre-populate it with a default or previously set value) then you could do this by using constants or state and adding `text=“{bar}”` to the UITextField xml, where bar would be the name of the constant or state variable.

**Comment by den2k** [comment]
Thanks. Looks like its working. Here is what I did which may help others.

```
class LoginScreen: UIViewController, LayoutLoading, UITextFieldDelegate
{
    @IBOutlet var emailTextField : UITextField?
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.loadLayout(
            named: "LoginScreen.xml",
            state:[
                "email": emailTextField?.text as Any,
            ]
        )
    }
}
```

```
<UIView>
    <!-- email -->
    <UITextField
        outlet="emailTextField"
        placeholder="enter your email"
        text="{email}"
        left="50% - width/2"
        width="100% - 40"
        height="45"
        layer.cornerRadius="5"
        textAlignment="center"
    />
</UIView>
```
