### ISSUE TITLE
LayoutNode are never released

### ISSUE THREAD

**Issue by SilverTab** [schibsted/layout#139]
I'm not sure what I am doing wrong, I have a simple view controller with a UICollectionView, and I am using Layout for both the view controller and the cells in the collection view, however, it looks like all the LayoutNodes that are created are never released... Just going back and forth to that view controller quick leads to an out of memory crash.

I've peaked at the memory graph but didn't find anything useful (other than seeing a ton of LayoutNodes all over the place, that retain other LayoutNodes, etc.)

I decided to simplify (a lot) and just went with a blank project that just has 2 view controllers, one (non-layout backed) that has a button that displays the 2nd view controller modally (a simple layout-backed view controller that has a label, an image view, and a button to dismiss it).

After tapping the button a couple of times, I peaked at the memory graph. Surely enough, all the layout nodes are still there ( even though the layout-backed view controller itself isn't in memory anymore ). I figured maybe this was on purpose, but apparently all these layout nodes are also retaining all the views they contain, so showing and dismissing the layout view controller 10 times for example, I end up with 10 image view instances, 10 buttons, 10 labels, etc. that are leaked.

Am I doing something wrong? I can put together a simple test project to show the issue, but it looks like pretty much any LayoutNode I create, no matter how, are just never released so it should be fairly easy to repro...

**Comment by SilverTab** [comment]
Here's what the memory graph looks like for these leaked LayoutNodes:
https://i.imgur.com/vClCQNX.png

And here are for example, the leaked image views contained in the leaked layout nodes:
https://i.imgur.com/H1dv1ZG.png

**Comment by nicklockwood** [comment]
Thanks, I’ll see if I can repro.

**Comment by nicklockwood** [comment]
@SilverTab OK, the leak seems to have been introduced in 0.6.28. Try using 0.6.27 for now and I'll work on a fix.

**Comment by SilverTab** [comment]
Unfortunately, I can repro it in 0.6.27: https://i.imgur.com/pxfcD9v.png

And my simple test project was actually using an even older version (0.6.18).

**Comment by nicklockwood** [comment]
@SilverTab in that case, can you upload your test project? I think it might be a different issue from what I'm seeing.

**Comment by SilverTab** [comment]
Here you go:

Steps to repro:

1) Run the app
2) Tap on the button to show the layout-backed view controller
3) Tap button to dismiss newly shown view controller.
4) Repeat 10-12 times
5) Hit the Debug Memory Graph button.
6) Filter the list of objects in memory for "LayoutNode" to see all the nodes still in memory, and then filter it for "ImageView", to see that all the views are also still in memory.

[LayoutLeaks.zip](https://github.com/schibsted/layout/files/2249881/LayoutLeaks.zip)

**Comment by nicklockwood** [comment]
@SilverTab this is fixed in version 0.6.29. Thanks for reporting it!

**Comment by SilverTab** [comment]
@nicklockwood Woo! Can confirm that the new version appears to fix all the leaks I was seeing in both projects where I am using Layout! 👍

**Comment by TwunTee** [comment]
I am facing this problem when i reload the layouts using cmd + R. I am assuming it might be the same issue, I have a similar app structure too will test out and see if I am getting the same issue

**Comment by nicklockwood** [comment]
@SilverTab I've found the problem. Can you believe it was a single missing `weak`?! anyway, version 0.6.30 includes the fix.

@TwunTee can you try to reproduce your issue with 0.6.30? If it's still happening, please open a new ticket, as it's probably a separate issue

**Comment by SilverTab** [comment]
@nicklockwood I can totally believe it, as I've been bitten before too :P 

Can confirm that there seems to be no leaks now! Woo!
