### ISSUE TITLE
Layout error: Layout found multiple source files matching /en.lproj/Localizable.strings

### ISSUE THREAD

**Issue by jhays** [schibsted/layout#140]
I am attempting to use another library (ZendeskSDK) that requires importing a .bundle file alongside their framework into the project. This bundle contains its own Localizable.strings files. After importing this bundle and running the app, Layout fails and prints the following line many times to the log:

> Layout error: Layout found multiple source files matching /en.lproj/Localizable.strings

Views using Layout and attempting to read from the app's Localizable.strings file end up broken. 

Is there any way around this issue? Could Layout be configured to only check the main bundle for Localizable.strings and not conflict with files of the same name within embedded bundles? 

Thanks.

**Comment by jhays** [comment]
Hi Nick, 

No, I am not seeing that screen when running my project in simulator. Instead I see a mostly black, broken layout of my root view. (It seems the elements that are broken are referencing localized strings)

I've recreated the issue in a sample project here, the additional conflicting strings file is within the Zendesk bundle: 
https://www.dropbox.com/s/9yoxzffguxm7f2p/LayoutExample.zip?dl=0

I've been looking for a solution by extending `LayoutLoader` and modifying `loadLocalizedStrings`  but it seems that's out of reach due to access control. If I build my own version of the Layout framework and modify that method to load a different file such as `LayoutLocalizable.strings` it resolves the conflict, but I'm hoping there is a better solution. If you've got any other suggestions it would be much appreciated! 

Thanks,
-Julian

**Comment by nicklockwood** [comment]
@jhays OK, it seems to be because of Carthage. For some reason when you use Carthage to integrate Layout then `#if DEBUG` within the framework, even if you're running in debug mode. I'll see if I can find a workaround for this, but in the meantime you can work around it by adding this code inside `application(_:didFinishLaunchingWithOptions:)` (or wherever seems appropriate):

    #if DEBUG
    LayoutConsole.isEnabled = true
    #endif

**Comment by jhays** [comment]
Great, thank you for the help!
