### ISSUE TITLE
Correct method to use for setting TableView Cell view data

### ISSUE THREAD

**Issue by TwunTee** [schibsted/layout#141]
I have a custom tableview cell defined in its own class and I have linked few outlets. setLayoutState seems to be working without any problem, but when i am trying to access the outlets in  
```
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
```
I get nil outlets when scrolling, seems to be happening when the cell is reused. Is there any method which is called when the cell is shown

**Comment by nicklockwood** [comment]
@TwunTee you might need to call `setState()` or `update()` on the cell node before trying to reference the outlets.

**Comment by TwunTee** [comment]
I am accessing the outlets right after setState

**Comment by TwunTee** [comment]
```
    @IBOutlet var likeButton: DOFavoriteButton!
    var viewModel: StyleCellViewModel?
    func refreshState() {
        self.layoutNode?.setState(self.viewModel?.model!)
                        if let liked = self.viewModel?.model?.liked {
            self.likeButton?.isSelected = liked
        }
    }
```
I am calling refresh state method of the cell in  
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell

But likeButton seems to be nil when scrolling, its not nil initially

**Comment by nicklockwood** [comment]
@TwunTee hmm, that all looks correct. Can you upload a sample project so I can investigate?

**Comment by TwunTee** [comment]
It was a mistake on my end. One of the object inside the struct was nil and i was trying to access its property and that was causing the error. Thanks for helping out!!
