### ISSUE TITLE
How to use Bool variables with parameter passing?

### ISSUE THREAD

**Issue by den2k** [schibsted/layout#145]
I've been getting errors with the following example code and it may be syntax.   I can pass Strings using parameters but not having success with Bool.

Template.xml
```
 <param name="weekend" type="Bool" />

<UILabel
        isHidden="{weekend}"
        text="Weekend!"
        />
```

Separate file.xml
```
 <UIView
        template="Template.xml"
        weekend="true"
    />
```

**Comment by nicklockwood** [comment]
@den2k this looks correct to me. What happens when you try it?

**Comment by den2k** [comment]
it crashes.  I've since created a separate Bool param using the same code and it now works.  Not sure what I was doing wrong. closed issue unless I can reproduce this problem. thanks.
