### ISSUE TITLE
Anyone have trouble using outlets within a UITableViewCell.xml file?

### ISSUE THREAD

**Issue by den2k** [schibsted/layout#146]
This is the following code I'm having trouble with which produces the following error.

UITableViewCell does not have an outlet named journalTextView.....

The setState value for ""journal" works as well as other variables... so sure the issue. Scratching my head for 2 days off and on.

```
class TableScreen: UIViewController, UITableViewDataSource, UITableViewDelegate, UITextViewDelegate
{
    @IBOutlet var journalTextView: UITextView?
    @IBOutlet var TableView: UITableView? {
        didSet {
            TableView?.registerLayout(
                named: "Cell.xml",
                forCellReuseIdentifier: "Cell"
            )
        }
    }
....
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
{
        let cellNode = tableView.dequeueReusableCellNode(withIdentifier: "Cell", for: indexPath)

        cellNode.setState([
            "journal": journalTextView?.text as Any,
            ])
        return cellNode.view as! UITableViewCell
    }
```

TableScreen.xml

```
<TableScreen>
    <UITableView
        outlet="TableView"
        ...
        >
    </UITableView>
</TableScreen>
```

Cell.xml
```
<UITableViewCell
    reuseIdentifier="Cell"
    ....
    >
    ....
    <UIView>
        <UITextView
            outlet="journalTextView"
            text="{journal}"
           ...
        />
    </UIView>
</UITableViewCell>
```

**Comment by nicklockwood** [comment]
@den2k Layout only supports automatic binding of outlets in table view cell subviews to the cell itself.

If you want to bind an outlet for a view inside the cell to your view controller, you’ll need to do it manually inside the tableView(_:cellForRowAt:) method.

**Comment by den2k** [comment]
That sounds great! Just not sure how.. ;) .  I'm a novice to this so..

This is what I will experiment with.  Thanks for the quick response. 
```
class TableScreen: UIViewController, UITableViewDataSource, UITableViewDelegate, UITextViewDelegate
{
    @objc @IBOutlet var journalTextView: UITextView?
    ....

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
{
     ...
        self.cellNode = LayoutNode(
            view: UIView.self,
            children: [
                 LayoutNode(
                      view: UITextview.self,
                      outlet: #keyPath(self.journalTextView),
                 )
            ]
       )  
   ....
     return cellNode.view as! UITableViewCell
}
```

**Comment by den2k** [comment]
So I eventually added this to inside the tableView(_:cellForRowAt:) method with still not success... :( . I'll keep plugging away. 

In case you are wondering. This is the table view controller:  
https://github.com/den2k/TIMII/blob/master/TIMII/Views/TimelineTableScreen.swift

```
self.layoutNode = LayoutNode(
     view: UITableViewCell.self,
     children: [
          LayoutNode(
              view: UIView.self,
              children: [
                  LayoutNode(
                     view: UITextView.self,
                     outlet: #keyPath(journalTextView)
                 )
              ]
         )
     ]
 )
   ...
```

**Comment by den2k** [comment]
I'm really struggling to find an answer:

So far I've look at
- bind(:to)
- outlet: #keyPath
- weird hacks.

I doubt I'm doing this correctly so any support would be wonderful.

**Comment by nicklockwood** [comment]
@den2k sorry for not getting back sooner.

If I understand correctly, you are trying to store a reference to the `UITextView` inside your table cell in a property in your `TableScreen` `UIViewController` called `journalTextView`, and the set the text of the `UITextView` to match the last value it was set to whenever the cell is recycled so that you won't lose the text if the cell moves off the screen?

In general, if you have a nontrivial table cell layout, it's best to create a subclass to use for your cell, then you can bind subviews directly to the cell. So that would look something like this (this code is untested, so apologies if there are typos):

```swift
class MyCustomCell: UITableViewCell {
    @objc var journalTextView: UITextView?
}
```

```xml
<MyCustomCell
    reuseIdentifier="Cell"
    ....
    >
    ....
    <UIView>
        <UITextView
            outlet="journalTextView // this will be bound to the cell itself, not the view controller"
            text="{journal}"
           ...
        />
    </UIView>
</MyCustomCell>
```

Once you have that, you can then reference the `journalTextView` directly from the cell, by using:

```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
{
    let cellNode = tableView.dequeueReusableCellNode(withIdentifier: "Cell", for: indexPath)
    cellNode.setState([
        "journal": journalTextView?.text as Any,
    ])
    let cell = cellNode.view as! MyCustomCell
    // copy the journalTextView property of the cell to the journalTextView property of the controller
    self. journalTextView = cell.journalTextView
    return cell
}
```

Let me know if that doesn't work.

**Comment by den2k** [comment]
I can now pull value back into the controller from my UITextView. There is a separate issue but should not be related to Layout, so THANKS!
