### ISSUE TITLE
EKEventEditViewController cells are tiny whenever the 'Layout' pod is included in my project

### ISSUE THREAD

**Issue by bourquep** [schibsted/layout#147]
See the [attached Xcode project](https://github.com/schibsted/layout/files/2451361/EKTest.zip) for a repro, which consists of a plain view controller which presents an `EKEventEditViewController` modally.

Here's what it looks without the `Layout` pod (simply comment out the `pod Layout` line in the podfile, or run the project before doing `pod install`):

<img width="526" alt="image" src="https://user-images.githubusercontent.com/65096/46548959-8796e000-c89e-11e8-896f-b97f24e9c129.png">

Here's what it looks like with the `Layout` pod installed. Note that I am not importing nor using Layout in this project, I am just including the framework.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/65096/46549031-bf058c80-c89e-11e8-81db-06923c01ea1b.png">

**Comment by nicklockwood** [comment]
@bourquep fixed in Layout 0.6.31. Thanks for reporting it!
