### ISSUE TITLE
Macro for font name is not working

### ISSUE THREAD

**Issue by algrid** [schibsted/layout#155]
Hello,

I'm trying to use a macro for a `UILabel` font like this:

```xml
    <macro name="TITLE_W" value="66%"/>  
    <macro name="TITLE_FONT" value="Roboto-Medium 13"/>

    <UILabel
        top="previous.bottom + 12"
        left="parent.left"
        width="TITLE_W"
        font="TITLE_FONT"
        text="some text"/>
```

It works fine with the `TITLE_W` but for `TITLE_FONT` I get:

```
Invalid font name or specifier TITLE_FONT.
```

It would be nice to have this feature supported.

**Comment by nicklockwood** [comment]
@algrid try`font="{TITLE_FONT}"` instead.

**Comment by algrid** [comment]
@nicklockwood Tried that, I'm getting "Unexpected token `13` in font expression in UILabel...".

When I use `Roboto-Medium 13` directly it works fine.

**Comment by algrid** [comment]
@nicklockwood 
This time I get:
<img width="358" alt="screen shot 2018-10-31 at 1 30 10 pm" src="https://user-images.githubusercontent.com/6792526/47785354-29301680-dd11-11e8-9a62-63ab29bee77c.png">

Maybe it's interpreting that dash as a minus sign and trying to calculate it...

It's not critical for me now, just wanted to report it :)

**Comment by nicklockwood** [comment]
@algrid ah, I think I see the problem. It's interpreting `Roboto-Medium 13` as an expression, not a string. try:

```xml
    <macro name="TITLE_W" value="66%"/>  
    <macro name="TITLE_FONT" value="'Roboto-Medium 13'"/>

    <UILabel
        top="previous.bottom + 12"
        left="parent.left"
        width="TITLE_W"
        font="TITLE_FONT"
        text="some text"/>
```

(Note the single ' ' quotes around 'Roboto-Medium 13')

**Comment by algrid** [comment]
@nicklockwood 

Works like this:

```xml
    <macro name="TITLE_W" value="66%"/>  
    <macro name="TITLE_FONT" value="'Roboto-Medium 13'"/>

    <UILabel
        top="previous.bottom + 12"
        left="parent.left"
        width="TITLE_W"
        font="{TITLE_FONT}"
        text="some text"/>
```

Thanks!
