### ISSUE TITLE
Weird Bug when using two different custom cellview in different tableviews

### ISSUE THREAD

**Issue by TwunTee** [schibsted/layout#157]
I am facing a strange bug where the content overlaps like a glitch in tableview. I am using tabbar with two view controllers and each viewcontroller has a tableview with different single custom cell. The first viewcontroller seems  to have no problem initially but if i switch tab the second viewcontroller would be messed up and then i come back to the first it would get messed up too as i scroll. If I use same custom cell in both the tableview it doesn't happen but if i use different one in different tableview with different reuseIdentifier the glitch happens

**Comment by TwunTee** [comment]
When using same cell - https://vimeo.com/user91355387/review/298820529/114fdca082
When using different cell - https://vimeo.com/user91355387/review/298820539/5ec6e70cf4

Tried changing the cells between view controllers keeping same layout still the same problem happens

**Comment by TwunTee** [comment]
https://github.com/TwunTee/LayoutBug

Made a sample project for the bug

**Comment by nicklockwood** [comment]
@TwunTee there doesn't seem to be an Xcode project in the sample you uploaded.

**Comment by TwunTee** [comment]
I corrected the error. I wanted to strip off the company details as I was using my office desktop

**Comment by TwunTee** [comment]
@nicklockwood Any idea what might be causing the problem and are there any way to reference outlets without using a custom cell. Any workaround or help would be great. Please do let me know if I can make it easier to debug

**Comment by TwunTee** [comment]
After trying out various things I remembered not having this problem before so I downgraded and it seems to have fixed the problem. The problem seems to be happening with versions after 0.6.30. I downgraded to 0.6.30 and the bug disappeared.

**Comment by nicklockwood** [comment]
@TwunTee sorry for not getting back to you sooner. I believe I've fixed this in the latest release (0.6.34), but let me know if it's still happening.

**Comment by TwunTee** [comment]
The latest release fixes that issue, thanks!!
