### ISSUE TITLE
Guides for contributors

### ISSUE THREAD

**Issue by mkarp** [schibsted/layout#20]
Hey @nicklockwood! I would appreciate if you could publish a guide for contributors. I would like to make a pull request with some code changes and I don't know what your requirements are. I'd appreciate even a short outline of points.

First thing I'd like to know is what source file header comment to use. Is `//  Copyright © 2017 Schibsted. All rights reserved.` the one I should be using, even though I don't work for Schibsted?

**Comment by nicklockwood** [comment]
Yeah, I should add a contributing document.

If you're planning a significant feature or refactor, can you give me a brief outline of what you're planning? I don't want you to waste a lot of time if it's not something that's likely to be accepted.

**Comment by mkarp** [comment]
I have some ideas for future contributions, however as I haven't used Layout yet in the real world so to say, I don't have any plans for feature or refactoring.

And for the thing I'm working on at the moment, I've opened a separate issue: https://github.com/schibsted/layout/issues/21

**Comment by nicklockwood** [comment]
@mkarp How about this? https://github.com/schibsted/layout/blob/82b6bab9c15765d2af189add3f9ccbc09377498a/CONTRIBUTING.md

**Comment by mkarp** [comment]
Very nice, thank you!

One thing that made me think for a moment when creating a new PR: what file header to use for a newly created file? It mentions a copyright to Schibsted, and I wondered whether I should use it too. It would be awesome if you could clarify this point.

Nevertheless, I think the guide in its current state is already helpful, so please feel free to close this issue.

**Comment by 3lvis** [comment]
👏
