### ISSUE TITLE
Feature proposal: make  LayoutTool return unix exit codes

### ISSUE THREAD

**Issue by mkarp** [schibsted/layout#21]
I'm currently working on a small thing when I'd like the LayoutTool to return unix exit codes: 0 for success, 1 for error. If LayoutTool is hooked in Build Phases, with proper exit codes Xcode will fail the build early if formatting fails. @nicklockwood do you think it's an addition worth doing?

**Comment by nicklockwood** [comment]
Yes please, that sounds great.

**Comment by mkarp** [comment]
@nicklockwood There's one more thing that I'd like your input on. Currently, LayoutTool adds red colour to the error messages, which I think is very nice.

TIL Xcode has a useful feature: if output to the stderr contains an `error:` prefix, then this output will be shown among the errors. Compare these two screens:

<img width="1072" alt="screen shot 2017-08-12 at 14 05 07" src="https://user-images.githubusercontent.com/318902/29240617-f309f1fe-7f68-11e7-9e83-0d7359f09ac0.png">
<img width="1072" alt="screen shot 2017-08-12 at 14 16 45" src="https://user-images.githubusercontent.com/318902/29240618-f32d07ac-7f68-11e7-8db8-7da2c290ae74.png">

I think the latter is much better for the feedback to a developer.

As you know and have implemented, colouring of the output is done by adding a special prefix and a suffix to it (`\u{001B}[31m{output}\u{001B}[0m` for the red colour). And this special prefix doesn't go along with Xcode's expectation for the `error:` prefix: `\u{001B}[31merror:` doesn't work.

I'd like to propose two options to make error messages from LayoutTool to appear in Xcode's errors pane:

1. Remove colouring of the output. Looks less nicer when LayoutTool is used in Terminal, however easy to implement. Why I think it's a viable option: as a user of the library, I see myself using LayoutTool within the Build Phases, however not so often in the Terminal.
1. Add support for an `--xcode` command line argument. When it's present, LayoutTool would not add colour specifiers to the output. This option is more flexible and requires more work.

What do you think?

**Comment by nicklockwood** [comment]
Interesting. I'm curious how other tools handle this, as a lot of them use colors. Maybe the best option would be to display the errors themselves without color and then print a final success/failure message in red?

**Comment by nicklockwood** [comment]
@mkarp I've pushed some changes that solve this in the way I suggested. Let me know if that works for you.

**Comment by nicklockwood** [comment]
Implemented in 0.4.11

**Comment by mkarp** [comment]
@nicklockwood Thank you very much! Works beautifully. However errors reported previously were a bit more descriptive:

<img width="1072" alt="screen shot 2017-08-14 at 20 51 38" src="https://user-images.githubusercontent.com/318902/29286444-6031578e-8132-11e7-9450-24b8d7e1498b.png">

I think that "XML validation error at {line}:{column}" gave better indication for the problems in XML files.

**Comment by nicklockwood** [comment]
Oh, that's curious. That wasn't an intentional change. What XML produced that error?

**Comment by mkarp** [comment]
I intentionally broken it (for testing purposes) with

```
<UILabel>
Hello world
</Something went wrong>
```

Pretty much as on one of the screenshots above.

**Comment by mkarp** [comment]
Apologies that the XML example is missing angle brackets — I'm writing from a phone and the app probably did some unintentional cleanup

**Comment by nicklockwood** [comment]
@mkarp Sorry, it looks like I broke error messages in a subsequent refactor after making them work nicely :0) I've pushed a fixed version to master, and added a test so I don't break them again.
