### ISSUE TITLE
Height is not calculated correctly for table view cells when text or detail text labels contain multiline text

### ISSUE THREAD

**Issue by vmagaziy** [schibsted/layout#33]
Use sample application and change `text` of `textLabel` for `UITableView` to make it long enough and set `textLabel.numberOfLines="0"` to make text label multiline and observe the following:

![simulator screen shot 23 aug 2017 14 10 29](https://user-images.githubusercontent.com/1112653/29615323-c5f90602-880d-11e7-8099-3edc93473169.png)

The same issue can be observed when `detailTextLabel` contains multiline text. It's a bug of iOS (for additional details see [this workaround](https://github.com/tiritea/MultilineTableViewCell) or [this discussion](https://stackoverflow.com/questions/36587126/autolayout-ignores-multi-line-detailtextlabel-when-calculating-uitableviewcell-h)), but apparently it gets fixed as of iOS 11, so it makes sense to address calculation for this case as well.

**Comment by nicklockwood** [comment]
I'll see what I can do about this. In the meantime, adding your own UILabel to the cell as a subview should work correctly.

**Comment by nicklockwood** [comment]
OK, I believe this is fixed in 0.4.17. I'm still seeing some funky spacing when using multiline `detailTextLabel`, but it sounds like that's a known issue in iOS per your comment.
