### ISSUE TITLE
Stackview

### ISSUE THREAD

**Issue by nixterrimus** [schibsted/layout#35]
I spent a couple of minutes with Layout today and it's excellent!  I'm still figuring out how I can make use of it and I immediately wondered about using stacks.  They make life much easier in UIKit (UIStackView) and React Native (Flexbox).   I looked through the docs and didn't see anything about stacks, did I miss it?

There are many cases where I'd like to distribute the content to take up all of the available space and a stack would be helpful to do it.

Here's a couple of examples where I want stacks:

![screen shot 2017-08-23 at 3 24 31 pm](https://user-images.githubusercontent.com/18454/29641185-3b6214fc-8817-11e7-9121-42e3c07616fa.png)

I'm kind of getting at the stack idea by setting relative to the previous's bottom:

```
<UIView
    width="100%"
    height="100%"
    backgroundColor="white">
        <UIView height="auto">
            <UILabel 
                font="16 bold"
                text="DRESS FOR TODAY"
                width="100%"
                textAlignment="center"
                top="20"
            />
            <UILabel 
                text="62°"
                font="28 bold"
                textAlignment="center"
                width="100%"
                top="previous.bottom + 10"/>
            <UILabel
                text="San Francisco, CA"
                font="16"
                top="previous.bottom + 10"
                width="100%"
                textAlignment="center"
                />
        </UIView>
        <UIView height="parent.height - previous.height - 80" top="previous.bottom" backgroundColor="yellow">
            <UILabel
            text="Info about today"
            top="previous.bottom"
            width="100%"
            textAlignment="center"
            />
        </UIView>
        <UIView height="80" backgroundColor="red" top="previous.bottom">
            <UIView xml="Day.xml"></UIView>
            <UIView xml="Day.xml" left="previous.right + 10"></UIView>
            <UIView xml="Day.xml" left="previous.right + 10"></UIView>
            <UIView xml="Day.xml" left="previous.right + 10"></UIView>
            <UIView xml="Day.xml" left="previous.right + 10"></UIView>
        </UIView>
</UIView>
```

This doesn't work so well with the days at the bottom.

Thank you for making this library- I kept hoping someone would make something like this!

**Comment by nicklockwood** [comment]
`UIStackView` is fully supported. You can use it in XML just as you'd expect. Children nodes in a `UIStackView` are automatically added to `arrangedSubviews`.

**Comment by nicklockwood** [comment]
Thanks for raising the lack of documentation - I'll fix that.

**Comment by nicklockwood** [comment]
Hmm, checking it now, it looks like there have been some regressions in UIStackView support - notably using a StackView causes errors after a reload. I'll try to land a fix for that asap.

**Comment by nicklockwood** [comment]
OK, I've fixed the regression and added some docs to the README in version 0.4.16

**Comment by nixterrimus** [comment]
Thanks!
