### ISSUE TITLE
UISegmentedControl support?

### ISSUE THREAD

**Issue by nextriot** [schibsted/layout#40]
Hi! Awesome work.

Is there support for UISegmentedControl? I tried the following:

```
<UISegmentedControl
    items="['A', 'B']"
    children="['A', 'B']"
    width="100%"
    top="previous.bottom + 10">
</UISegmentedControl>
```

Clearly I have a fundamental misunderstanding of how the element is supposed to work. It doesn't throw an error for the overall element, but does for both `items` & `children` properties.

I tried nesting elements within the control - also to no avail.

Is there some documentation that I missed that lists properties on a per element basis?

Thanks in advance for any help you can lend.

**Comment by nicklockwood** [comment]
@nextriot UISegmentedControl is not really supported yet. You might be able to make it work by passing items in as a constant or state variable from native Swift code, but there's currently no way to specify array literals using expressions in XML.

**Comment by nextriot** [comment]
@nicklockwood thanks for the speedy reply!

So given that I now have access to the constant in the xml, how would I then pass this as an attribute to the controller given that `items` is still seen as an unknown property? I went through the section on constants, but I'm not seeing a clear-cut way that specifies that.

```
self.loadLayout(
    named: "Label.xml",
    constants: [
        "items": ["A", "B"]
    ]
)

<UISegmentedControl
    width="100%"
    top="previous.bottom + 10"
    items="{items}"
/>
```

**Comment by nicklockwood** [comment]
@nextriot sorry, I should have checked the UISegmentedControl API more carefully - it seems that items isn't a real property, it's just a constructor argument for init, which isn't available in Layout without a custom extension.

The only way you can do it for now is to create an outlet for the UISegmentedControl and then set the items programmatically. Something like this:

```xml
<UISegmentedControl
    outlet="segmentedControl"
    width="100%"
    top="previous.bottom + 10"
/>
```

Then in your view controller:

```swift
@IBOutlet weak var segmentedControl: UISegmentedControl? {
    didSet {
        segmentedControl?.insertSegment(withTitle: "A", at segment: 0, animated: false)
        segmentedControl?.insertSegment(withTitle: "B", at segment: 1, animated: false)
    }
}
```

Or alternatively:

```swift
@IBOutlet weak var segmentedControl: UISegmentedControl?

override open func layoutDidLoad() {
     segmentedControl?.insertSegment(withTitle: "A", at segment: 0, animated: false)
     segmentedControl?.insertSegment(withTitle: "B", at segment: 1, animated: false)
}
```

I know that's not very satisfactory. I'll try to add proper support for UISegmentedControl in the next release.

**Comment by nextriot** [comment]
That's brilliant! Thanks again @nicklockwood. Looking forward to it.

**Comment by nicklockwood** [comment]
OK, I've added improved support for UISegmentedControl in 0.4.18. This should now work:

```swift
self.loadLayout(
    named: "Label.xml",
    constants: [
        "items": ["A", "B"]
    ]
)

<UISegmentedControl
    width="100%"
    top="previous.bottom + 10"
    items="{items}"
/>
```
