### ISSUE TITLE
Extending a custom view with an initializer?

### ISSUE THREAD

**Issue by nextriot** [schibsted/layout#41]
Hi again!

I'm trying to extend the lottie framework so that I can use it with layout. 
The initializer for LOTAnimationView takes a `name` argument specifying the json filename you are looking to animate.
After reading through the [Custom Property Types](https://github.com/schibsted/layout#custom-property-types) section - I was hoping to be able to extend the view so that I could declare the image in the xml file via an attribute i.e.

```
<LOTAnimationView
    name="IMAGE_NAME"
/>
```

However, it seems as though it must be added at declaration, not after. Is there anyway to use the extension to add an initializer that would allow me to do the above?

**Comment by nicklockwood** [comment]
It's not documented because it's a bit experimental, but something like this should work:

```swift
extension LOTAnimationView {
    open override class func create(with node: LayoutNode) throws -> LOTAnimationView {
        guard let name = node.expressions["name"] else {
            throw LayoutError("name is required")
        }
        return self.init(name: name)
    }

    open override class var expressionTypes: [String: RuntimeType] {
        var types = super.expressionTypes
        types["name"] = RuntimeType(String.self)
        return types
    }

    open override func setValue(_ value: Any, forExpression name: String) throws {
        switch name {
        case "name":
            break // Ignore this - we set it during creation
        default:
            try super.setValue(value, forExpression: name)
        }
    }
}
```

Note that this will only work with a hard-coded name string in your XML though, it won't let you use an expression. There is a mechanism for that, but it's currently private.

**Comment by nicklockwood** [comment]
I've added a better API for this in 0.4.18. It's documented in the README, but in short the above can now be simplified to the following, and will now work with any expression for "name", not just a hard-coded value:

```swift
extension LOTAnimationView {
    open override class func create(with node: LayoutNode) throws -> LOTAnimationView {
        guard let name = try node.value(forExpression: "name") else {
            throw LayoutError("name is required")
        }
        return self.init(name: name)
    }

    open override class var parameterTypes: [String: RuntimeType] {
        return ["name": RuntimeType(String.self)]
    }
}
