### ISSUE TITLE
How should the XML look for a UINavigationController?

### ISSUE THREAD

**Issue by patchthecode** [schibsted/layout#43]
**Version**: 0.4.17
**Xcode**: 9.6 Beta
**SampleCode**: [LayoutsSample](https://github.com/patchthecode/layoutTests)

The goal is to have a simple `UINavigationController` with a root `viewController`.
It will have a custom navigation bar, hence I am trying to design the navigationBar in XML.

Something like this
<img width="254" alt="screen shot 2017-08-30 at 5 44 31 pm" src="https://user-images.githubusercontent.com/2439146/29901098-f4feb71a-8daa-11e7-9936-54e13ca70964.png">

I do not know how to get the UINavigationBar instance to customize it.
The link to my sample project is above. 
Here is my code so far.
```xml
// Bootstrap.xml
<UINavigationController>
    <UINavigationBar>
    </UINavigationBar>
    
    <UIViewController>
    </UIViewController>

</UINavigationController>
```

```swift
class ViewController: LayoutViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        loadLayout(named: "Bootstrap.xml")        
    }
}
```

This code causes the app to crash
```xml
<UINavigationBar>
</UINavigationBar>
```
So I needed help on the following:

1. Using your library, how do I get the instance of the UINavigationBar from the parent UINavigationController so that i can customize it?

As I learn more, I'll update the sample project link above. Thanks.

**Comment by patchthecode** [comment]
update: If i put the xml like this, then it no longer crashes

```xml
// Bootstrap.xml
<UINavigationController>    
    <UIViewController>
    </UIViewController>

    <UINavigationBar>
    </UINavigationBar>

</UINavigationController>
```

However, i see that there are 2 Navigation bars
<img width="300" alt="screen shot 2017-08-30 at 8 04 33 pm" src="https://user-images.githubusercontent.com/2439146/29904606-7bc02e06-8dbe-11e7-91fd-344243c092c4.png">

Therefore i think that i am still not doing it correctly.

**Comment by nicklockwood** [comment]
Customizing the navigation bar for UINavigationController is not currently supported in Layout. YOu'll have to do this part in code.

**Comment by patchthecode** [comment]
I looked at your contribution guidelines. If i have the spare time I would not mind looking into things like this and maybe doing a pull request.

How does one go about putting in a new feature like this or (other features)? I know it wont be possible to explain everything here, but is there some pattern you follow, or place you put the additions? And maybe is there anything major i need to watchout for? If i code nonsense you can always correct me haha.

**Comment by nicklockwood** [comment]
I've added improved support for this in 0.4.18. It's fully documented in the README, but it should now work in the way you were attempting to use it. Let me know if there is anything else missing.

**Comment by patchthecode** [comment]
Awesome. I'll check out now.
