### ISSUE TITLE
UIAlertController has missing UIAlertActions

### ISSUE THREAD

**Issue by Eddpt** [schibsted/layout#47]
When using `Layout` all the `UIAlertControllers` seem to have missing `UIAlertActions`, only on iOS 9.

```
private func presentAlert() {
    let sheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)

    sheet.addAction(UIAlertAction(title: "Edit", style: .default, handler: nil))
    sheet.addAction(UIAlertAction(title: "Delete", style: .destructive, handler: nil))
    sheet.addAction(UIAlertAction(title: "cancel", style: .cancel, handler: nil))

    present(sheet, animated: true)
}
```

![screenshot 2017-09-05 12 39 04](https://user-images.githubusercontent.com/1426933/30059495-38780c22-9237-11e7-93f3-0d0716667c64.png)

See the following [sample project](https://github.com/Eddpt/AlertTestWithLayout)

When using `Layout` version `0.4.13` it works fine, but upgrading to `0.4.14` or greater breaks.

<img width="1650" alt="screenshot 2017-09-05 12 38 14" src="https://user-images.githubusercontent.com/1426933/30059482-2df97cfe-9237-11e7-8377-ccaff29b1691.png">

From inspecting the views, it does seem that Apple uses a `UICollectionView` to present the Sheet, so perhaps that's a good hint of where the issue might be.

**Comment by nicklockwood** [comment]
Thanks! I've got a fix - I've pushed a fix to the develop branch.

**Comment by Eddpt** [comment]
Working 👍
