### ISSUE TITLE
Referencing elements inside XML

### ISSUE THREAD

**Issue by eimantas** [schibsted/layout#5]
How can I reference a sibling by its name inside an xml file? Let's say I'd like to have a couple of buttons aligned vertically. For now I found that I can only use `top` attribute with value relative to the elements parent (thus making it bigger the lower I want my button to go).

Can I somehow write an expression that I want my current button have vertical spacing of 8pt to the button before it?

**Comment by nicklockwood** [comment]
You can reference properties of the previous or next siblings using `previous` and `next` respectively. So to position a button 8pts below the previous element, you'd say:

    <UIButton top="previous.bottom + 8"/>

If there is no previous sibling, `previous.bottom` will be zero.

**Comment by eimantas** [comment]
This works. Thanks!

**Comment by silentninja** [comment]
Can we use the outlet property to reference the layout node  My use case is that I want a layout which is similar to the below layout.

````
[Label]

Some Text Lorem ipsum dolor sit amet, ut eos dicta malorum detracto, eruditi sensibus vix in, oblique
      [View]
````
The view start should be aligned to the end of the label. Instead of traversing the previous node, referencing by an identified would be a better option.

**Comment by nicklockwood** [comment]
This is not currently possible, although I’m working on a solution. Using `previous.previous.right` should work for now, although I agree it’s not ideal.

**Comment by silentninja** [comment]
I ended up doing it. Thanks for confirming.

**Comment by nicklockwood** [comment]
@silentninja I've put up a PR for referencing nodes by ID, so that should be included in the next release: https://github.com/schibsted/layout/pull/61
