### ISSUE TITLE
UIButton-UIControlState-backgroundColor

### ISSUE THREAD

**Issue by geGao123** [schibsted/layout#53]
hope UIButton can set backgroundColor with state(normal,highlighted...),just like backgroundImage.i think it's will be very nice.
thx.(also i think Layout is a very good,Especially for someone develope android  before)

**Comment by nicklockwood** [comment]
Unfortunately UIButton doesn't support this feature itself, which is why I haven't exposed it in Layout. The best option is to create a background image with a solid color, which you can do like this:

    extension UIImage {
        static func imageWithColor(_ color: UIColor) -> UIImage {
            UIGraphicsBeginImageContextWithOptions(CGSize(width: 1, height: 1), false, 1)
            defer {
                UIGraphicsEndImageContext()
            }
            color.setFill()
            UIRectFill(CGRect(origin: .zero, size: CGSize(width: 1, height: 1)))
            return UIGraphicsGetImageFromCurrentImageContext()!.resizableImage(withCapInsets: .zero)
        }
    }

**Comment by nicklockwood** [comment]
(Note: You'd have to pass some of these images in as constants to use them in Layout)

**Comment by geGao123** [comment]
thx
