### ISSUE TITLE
uncaught exception 'NSInvalidArgumentException', reason: 'UICollectionView must be initialized with a non-nil layout parameter'

### ISSUE THREAD

**Issue by sergeymild** [schibsted/layout#55]
I have this error after adding an outlet to UICollectionView.
Without outlet it's works as expected.

**Comment by nicklockwood** [comment]
Thanks for reporting. I'm having some trouble reproducing the issue - can you show me your project, or at least the XML and view controller?

**Comment by sergeymild** [comment]
All ok, sorry it was my problem. You make awesome tool.)
