### ISSUE TITLE
dtd for xml

### ISSUE THREAD

**Issue by geGao123** [schibsted/layout#57]
Is it possible to add dtd in the editor to get a code hint when layout in xml file?

**Comment by nicklockwood** [comment]
No, unfortunately. I tried this, but sadly Xcode and most other editors ignore external DTDs for autocomplete purposes.

If you use Sublime Text, there’s an autocomplete file included in the repository. That’s the best solution I can offer at the moment.

**Comment by 913868456** [comment]
but we need to switch two editors in Xcode and Sublime Text. Maybe that`s a bad experience 😭
