### ISSUE TITLE
[Question] how do you set UITableViewCell's accessoryView in XML

### ISSUE THREAD

**Issue by hermanccw** [schibsted/layout#59]
Can I do that inside an expression? If yes, how?

**Comment by nicklockwood** [comment]
You would have to pass it in as a constant from the Swift code. Currently there's no way to define it inline using an XML node.

**Comment by nicklockwood** [comment]
I think to do this safely you would either need to set it in the cellForRowAtIndexPath() method, or create a UITableViewCell subclass and set it inside there. If you passed it as a constant in the tableview setup code then it would try to use the same accessoryView instance for multiple cells, which won't work.

**Comment by hermanccw** [comment]
ok, thx
