### ISSUE TITLE
Unable to change collection view's cell size

### ISSUE THREAD

**Issue by eimantas** [schibsted/layout#6]
Version: 0.48
iOS Sim: 11.0
Xcode: 9b5

The `collectionViewLayout.itemSize` attributes in `<UICollectionView>` tag don't seem to affect the outcome of how the cell is displayed in the loaded view. Tried it out in custom view as well as sample application. Hardcoding values or setting them as expressions doesn't seem to change anything at all.

**Comment by nicklockwood** [comment]
This is a bug due to a misunderstanding of the collection view auto-sizing mechanism on my part. I'll put a fix in the next release, but for now a workaround is to add these attributes to your <UICollectionView>:

        collectionViewLayout.estimatedItemSize.width="0"
        collectionViewLayout.estimatedItemSize.height="0"
