### ISSUE TITLE
Using enum within XML layout

### ISSUE THREAD

**Issue by hermanccw** [schibsted/layout#63]
I have the following enum and viewmodel
```
enum PinCodeInputState {
  case Initial
  case Checking
  case Failed
  case Succeed
}

struct PinCodeInputViewModel {
  var pinCode: String = ""
  var state: PinCodeInputState = .Initial
}
```

and the following label in XML
```
<UILabel
        text="Invalid pin, please try again"
        textAlignment="center"
        textColor="red"
        top="previous.bottom + 10"
        width="100%"
        isHidden="{state == PinCodeInputState.Failed ? true : false}"
    />
```

When I try to setup the layout like this
```
loadLayout(
      named: "PinCodeInput.xml",
      state: PinCodeInputViewModel()
    )
```

it gives me the error: "Unknown property PinCodeInputState of UILabel for PinCodeINputState.Failed in `isHidden` expression in UIView

Is it possible to check enum value inside an expression?

**Comment by nicklockwood** [comment]
This isn’t currently possible, but I hope to support it soon. In the meantime, passing PinCodeInputState.Failed as a constant and then comparing against that might work.

**Comment by hermanccw** [comment]
ok thx.

**Comment by nicklockwood** [comment]
@hermanccw this should now be possible in version 0.5.6, although it may only work with lowercase enum case names.
