### ISSUE TITLE
Font Types

### ISSUE THREAD

**Issue by freynolds** [schibsted/layout#66]
Hi, first of all, love your library so far!
I'm having a bit of an issue setting a system font to heavy, idk if I'm writing it wrong or something is missing.
`font="System heavy 24"`
it works with bold, not with heavy

Thank you for your time
Best regards
Francisco

**Comment by nicklockwood** [comment]
Hi Francisco, heavy isn’t supported yet, but you can create a heavy font in Swift and then pass it into your layout as a constant.

**Comment by nicklockwood** [comment]
This is now supported in 0.5.8
