### ISSUE TITLE
Templates containing root view controllers subclassing LayoutViewController steal the refresh command

### ISSUE THREAD

**Issue by hartbit** [schibsted/layout#72]
I guess this is technically "normal behaviour", as Layout is not really made to have multiple `LayoutViewController`s  at the same time. But perhaps we could either make an exception for `UITabBarController` or `UINavigationController`, or perhaps output a warning in the console when a template contains a root `LayoutViewController`?

**Comment by nicklockwood** [comment]
I'd guess this is fixed now that the reload handler is a singleton? Let me know if you're still seeing it.
