### ISSUE TITLE
Support for Objective-C

### ISSUE THREAD

**Issue by rachelfong** [schibsted/layout#77]
I am currently working on a project which in built on Objective-C and would love to try out Layout.

Does this library support Objective-C projects?

**Comment by nicklockwood** [comment]
@rachelfong Layout doesn't officially support Objective-C, but parts of it might work, depending on what you want to do. Can you describe your use case?

**Comment by rachelfong** [comment]
@nicklockwood We are looking into creating an app without the use of Storyboards or Nibs and remotely configure the UI. 

Since Layout supports loading XMLs from URLs, we thought it would be good to be able to leverage on it. I guess the plan is to build the XML on server side and then send it over to mobile via an API and load the UI accordingly.

However, my current project is written in Objective-C and I can't seem to find a way to integrate Layout into it.

**Comment by nicklockwood** [comment]
@rachelfong I've looked into this, but it would be quite a lot of work to support Objective-C at the moment, because Objective-C cannot subclasses Swift classes, which is necessary if you want to use LayoutViewController.

**Comment by rachelfong** [comment]
@nicklockwood I see. Thanks for the information. Closing this issue.
