### ISSUE TITLE
Custom Constructor Arguments Alternative

### ISSUE THREAD

**Issue by silentninja** [schibsted/layout#81]
When trying to create a custom view which needs a constructor to be used, I am using the method in https://github.com/schibsted/layout#custom-constructor-arguments. When doing so I am getting the following error 
```
constructing an object of class type with a metatype value must use a 'required' initializer
```
It is actually an mistake on the custom view for not using a required initializer, but most libraries have only one way to initialize and their initializers dont have required init. A possible workaround would be great.

**Comment by nicklockwood** [comment]
@silentninja can you show me the code for your create method? I’m not sure I understand the issue.

**Comment by silentninja** [comment]
I am using this library https://github.com/xhamr/fave-button and created extension for it with the below code.

```
import FaveButton

extension FaveButton {

    open override class var parameterTypes: [String: RuntimeType] {
        return [
            "etIcon": RuntimeType(String.self)
        ]
    }


    open override class func create(with node: LayoutNode) throws -> FaveButton {
        if let etIcon = try node.value(forExpression: "etIcon") as? String {
            return self.init(frame: CGRect(x: 200, y: 200, width: 44, height: 44), faveIconNormal: UIImage(named: etIcon)

            )

        }
       return self.init(frame: .zero)
    }

}
```

**Comment by nicklockwood** [comment]
Instead of `return self.init(...)`, try writing `return FaveButton(...)` instead.

**Comment by silentninja** [comment]
That did the trick!! I totally forgot that create(with:) is called by Layout and wont cause recursion.
