### ISSUE TITLE
UIStackView issues in 0.6.2 (vs 0.5.7)

### ISSUE THREAD

**Issue by tomekc** [schibsted/layout#83]
I am trying to achieve pretty complex layout, similar to Facebook wall items: avatar, three lines of metadata right to it, and some text content below.

It worked almost well on 0.5.7, with interesting twist - setting *font* attribute to more than one label led to freezing application (infinite loop?). I went on and updated to latest version.

Now contents of UIStackView is collapsing, and barely one label is visible:

<img width="367" alt="screen shot 2017-11-15 at 17 08 06" src="https://user-images.githubusercontent.com/407463/32847753-2981e310-ca2b-11e7-919f-e9aa5ce0644a.png">

While on 0.5.7 it was not perfect, but much better:

<img width="371" alt="screen shot 2017-11-15 at 17 35 18" src="https://user-images.githubusercontent.com/407463/32847890-794cc4f0-ca2b-11e7-986b-d2f69d9e56ff.png">

I wonder if there are some rules I need to follow for layout to be correct? Should I try to keep Auto Layout magic happy? I appreciate any pointers what may be bad.

I am playing with example app and modifying TableCell.xml and refreshing:
```
<UITableViewCell
    height="auto + 20"
    reuseIdentifier="standaloneCell"
    selectedBackgroundView.backgroundColor="colors.red"
    >

    <UIStackView
        axis="vertical"
        top="10"
        left="20"
        right="100% - 20"
        spacing="20">

        <UIStackView
            axis="horizontal"
            left="0"
            width="100%"
            spacing="20">

            <UIImageView
                highlightedImage="{whiteImage}"
                image="{image}"
                tintColor="colors.red"
                top="20"
                width="50"
                height="50"
                />

            <UIStackView
                axis="vertical"
                spacing="6"
                >
                
                <UILabel
                    text="Tomek Corleone"                    
                />

                <!-- add a font attribute to label below for infinite loop (version 0.5.7) -->                  
                <UILabel
                    text="2 days ago"  
                    textColor="#8B858D"
                    />
                <UILabel
                    text="The message will send at 5pm"
                    font="12"
                    textColor="#8B858D"
                />

            </UIStackView>

        <!-- Metadata part -->
        </UIStackView>
        
        <UILabel
        text="All this dates, however, from some considerable time back. For more
        than thirty years now the Aire Saint-Mittre has presented a different
        appearance. One day the townspeople, far too inert and indifferent to
        derive any advantage from it, let it, for a trifling consideration,
        to some suburban wheelwrights, who turned it into a wood-yard."
        numberOfLines="0"
            />
    </UIStackView>
</UITableViewCell>

```

**Comment by nicklockwood** [comment]
Hi @tomekc, thanks for reporting this. There was a bug with StackViews introduced in 0.6.1. Can you try the latest develop branch? - I think it should have fixed your issue.

https://github.com/schibsted/layout/tree/develop

I couldn't reproduce the font issue, so let me know if that's still happening.

**Comment by tomekc** [comment]
Yes, thanks, it looks much better now.

<img width="375" alt="screen shot 2017-11-16 at 01 23 56" src="https://user-images.githubusercontent.com/407463/32867655-b8f1b78a-ca6e-11e7-9b31-1c8b74eac3cb.png">

I only wonder if something can be done to keep UIImage intrinsic size (now it gets expanded to fill the half width). I tried to raise `contentHuggingPriority` of the `UIImageView`,

```
contentHuggingPriority="500"
```

but ended up with freeze.

**Comment by tomekc** [comment]
I think I got it right by using less StackViews, and relying more on laying out plain UIViews as containers ;)

**Comment by nicklockwood** [comment]
@tomekc yes, that's definitely the approach I would recommend with Layout, but thanks for raising the issue, as I'd like to make StackViews work better if possible.

**Comment by patchthecode** [comment]
Is there a way to use a regular stackView in the mean time wile issue is resolved? I'm trying to make another look at https://github.com/schibsted/layout/issues/44
