### ISSUE TITLE
Reference(s) to UIImagePickerController cause App Store rejection

### ISSUE THREAD

**Issue by micpringle** [schibsted/layout#85]
It appears as though Layout causes apps to fall foul of one of Apple's App Store review guidelines. 

Since the framework includes references to `UIImagePickerController` the store assumes the app makes use of it, and therefore will reject an app that uses Layout unless it includes the `NSPhotoLibraryUsageDescription` key in its **info.plist** along with a reasonable description of *why* it needs access to the users photo library.

**Comment by nicklockwood** [comment]
@micpringle I've pushed a possible fix to the develop branch, but I'm unable to test it due to iTunes connect silently ignoring my test app upload. Perhaps you can try it?

    pod 'Layout', :git => 'https://github.com/schibsted/layout', :branch => 'develop'

**Comment by micpringle** [comment]
Hey @nicklockwood,

Apologies for the delay in getting back to you. I'll give this a shot now and get back to you immediately.

**Comment by nicklockwood** [comment]
@micpringle no problem at all, thanks!

**Comment by micpringle** [comment]
@nicklockwood What ever you changed _appears_ to have resolved the issue. 👍 

I switched the pod to dev, created a new archive, and then uploaded it via the Organizer. It was accepted by iTC and no issues were reported.

**Comment by nicklockwood** [comment]
@micpringle Awesome, thanks for the confirmation!

**Comment by nicklockwood** [comment]
Fixed in version 0.6.6
