### ISSUE TITLE
Passing the node as parameter to layoutDidLoad

### ISSUE THREAD

**Issue by mariob** [schibsted/layout#86]
Would be great if the node could be passed as parameter to the `layoutDidLoad()` function in `LayoutViewController`.

Passing the node means that the user doesn't have to deal with an optional `layoutNode` in the function body thus can remove an unnecessary guard or force unwrap.

Current solution:
```
override func layoutDidLoad() {
    // layoutNode is optional
   guard let layoutNode = layoutNode else { return }
  // layoutNode is not optional
}

```
Suggested solution:
```
override func layoutDidLoad(_ layoutNode: LayoutNode) {
    // layoutNode is not optional
}

```

I think the suggested solution is much cleaner because the `layoutDidLoad` function is actually only called if the node was successfully loaded. I don't think there will be a big impact on existing code. Most developers will probably remove a guard statement in the function and be fine.

I could do a PR if you're interested.

**Comment by nicklockwood** [comment]
This seems like a good idea. We'll need to deprecate the old `layoutDidLoad()` protocol method though, and make sure it is still called until it's been completely removed.

**Comment by mariob** [comment]
Agree! We could replace the old invocation of `layoutDidLoad` with the new parameterised callback in `didSet`. The default implementation of the new `layoutDidLoad` will call the old function.

If the new layoutDidLoad isn't overridden in the view controller we keep the same behaviour as previously. If the new `layoutDidLoad` is overridden, we simply assume that the old `layoutDidLoad` shouldn't be called. No breaking change :)

Example:

```
            if let layoutNode = layoutNode {
                do {
                    try layoutNode.mount(in: self)
                    if _error == nil {
                        layoutDidLoad(layoutNode) // New callback
                    }
                } catch {
                    layoutError(LayoutError(error, for: layoutNode))
                }
            }
```

```
    /// Called immediately after the layoutNode is set. Will not be called
    /// in the event of an error, or if layoutNode is set to nil
    open func layoutDidLoad(_ layoutNode: LayoutNode) {
        // Mimic old behaviour if not overriden
        layoutDidLoad()
    }

    /// Called immediately after the layoutNode is set. Will not be called
    /// in the event of an error, or if layoutNode is set to nil
    @available(*, deprecated, message: "Use layoutDidLoad(_ layoutNode: LayoutNode) instead")
    open func layoutDidLoad() {
        // Override in subclass
    }

```

What do you think, looks good? Maybe some corner case I haven't though of?

**Comment by nicklockwood** [comment]
@mariob your solution looks great, please go ahead and make a PR :-)

**Comment by mariob** [comment]
One minor issue... Calling the deprecated layoutDidLoad (from the new function) will generate a warning in Xcode. It seems like it's quite hard to suppress these kind of warnings in Swift (on a line level).

Any ideas?

**Comment by nicklockwood** [comment]
@mariob I don't think there's any way to suppress it - might just have to live with the warning until it's removed.
