### ISSUE TITLE
StackViews.testAutoSizeElementsInAutoSizedStack tests fails on the develop branch

### ISSUE THREAD

**Issue by mariob** [schibsted/layout#89]
There're two failing unit tests in `StackViews.testAutoSizeElementsInAutoSizedStack`.

The reason could be because of an update of Xcode which happened today (needed support for iOS 11.2). My Xcode version is 9.2 (9C40b).

See attached screen shots for more information.
<img width="912" alt="skarmavbild 2017-12-05 kl 16 44 56" src="https://user-images.githubusercontent.com/75208/33616023-ef2d15e8-d9db-11e7-8967-3c56450dc2d9.png">

<img width="870" alt="skarmavbild 2017-12-05 kl 16 45 13" src="https://user-images.githubusercontent.com/75208/33616027-f324d00a-d9db-11e7-8c3e-c09e70883c09.png">

**Comment by nicklockwood** [comment]
Thanks for bringing this to my attention!

**Comment by nicklockwood** [comment]
Fixed on the develop branch.

**Comment by mariob** [comment]
👍
