### ISSUE TITLE
UIImageView tintColor not implemented

### ISSUE THREAD

**Issue by pabloroca** [schibsted/layout#93]
This is not implemented.

Here you have some ways to implement it https://stackoverflow.com/questions/19274789/how-can-i-change-image-tintcolor-in-ios-and-watchkit

I like the solution from YannickSteph, but maybe we would need a new property indicating is a photo or not.

**Comment by nicklockwood** [comment]
The kind of tinting that YannickSteph is talking about is not a standard feature of UIImageView, and as such is out of scope for Layout. You would need to add this as an extension.

Ordinary use of `tintColor` to color images that use the `alwaysTemplate` rendering mode is fully supported by Layout already if you use XCAssets images (as explained in one of the other answers to that stackoverflow question).

If you want to tint images that you’ve downloaded remotely (using the technique from here https://github.com/schibsted/layout/issues/87) then you’ll probably need to configure the moa library to set the `alwaysTemplate` rendering mode on the image, as this is a property of the UIImage itself, not the UIImageView.

**Comment by pabloroca** [comment]
Thanks!
