### ISSUE TITLE
loadLayout causes infinite loop

### ISSUE THREAD

**Issue by tomekc** [schibsted/layout#94]
Not sure if it was my mistake, but following the manual I added loading code in `viewDidLoad`.
It ends up with an infinite loop. I am guessing it is caused by ***completeSetup*** method getting view, which causes UIViewController to load view again, and then rinse and repeat.

ViewController and XML are in a separate target (in attempt to modularize the app), and ViewController is instantiated programmatically.

Did I miss something obvious here?

Here's stacktrace:
```
#23	0x0000000107a5446c in -[UIViewController loadViewIfRequired] ()
#24	0x0000000107a548b9 in -[UIViewController view] ()
#25	0x0000000106f012a2 in LayoutNode.completeSetup() at .../Pods/Layout/Layout/LayoutNode.swift:110
#26	0x0000000106f3bee7 in LayoutNode.setUpExpressions() at .../Pods/Layout/Layout/LayoutNode.swift:1209
```

ViewController code:

```swift
    public override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.title = "CandidateList"
        print("Loading from XML layout")
        self.loadLayout(named: "CandidateList", bundle: Bundle(for: type(of: self)), constants: [:])
        

        // Do any additional setup after loading the view.
    }
```

And simple XML:
```xml
<CandidateList.CandidateList >
    <UITableView backgroundColor="tintColor"
        contentInset.bottom="safeAreaInsets.bottom"
        contentInset.top="safeAreaInsets.top"
        contentInsetAdjustmentBehavior="never"
        contentOffset.y="-safeAreaInsets.top"
        estimatedSectionHeaderHeight="20"
        outlet="tableView"
        scrollIndicatorInsets.bottom="safeAreaInsets.bottom"
        scrollIndicatorInsets.top="safeAreaInsets.top"
        style="plain">
        </UITableView>
</CandidateList.CandidateList >
```

**Comment by nicklockwood** [comment]
@tomekc is your view controller of class CandidateList?

If so, you probably need to remove the <CandidateList.CandidateList> root node from your XML, otherwise you are trying to load a new instance of the view controller into itself, hence the infinite loop.

I’ll try to make the error for this a bit clearer in the next version.

**Comment by tomekc** [comment]
@nicklockwood Thanks, removing root node helped!
And yes, it is. I think I copied that pattern from example project, where the VCs are a root element of XML.

**Comment by nicklockwood** [comment]
@tomekc yeah, the example is a bit unusual because the root node is a UITabBarController. It's fine to have a VC as the root node in your XML - it just can't be the *same* VC that you're trying to load the XML into.
