### ISSUE TITLE
Warning (console?) if an outlet is assign more than once

### ISSUE THREAD

**Issue by mariob** [schibsted/layout#98]
Just encounter this problem. Had two different views in different xml-files which was loaded from a main xml file (one was hidden when the other one was shown). By accident I had an outlet assign to a button from both views which of course gave some headache before I found out that the same outlet was assigned from both view and thus the first assignment was overwritten by the other one.

Would it be possible to detect this without too much performance penalty and log to the console that an outlet is assigned more than once.

**Comment by mariob** [comment]
I know that this shouldn't be a production problem. It's more of an help while developing.

**Comment by nicklockwood** [comment]
@mariob good idea - should be doable.

**Comment by nicklockwood** [comment]
@mariob OK, I've implemented this on the develop branch.

**Comment by mariob** [comment]
Tried it and 👌
