### ISSUE TITLE
Animate view's height when scroll

### ISSUE THREAD

**Issue by marciliojrs** [schibsted/layout#99]
Hi! I'm trying to implement a collapsable header for my scrollview with Layout. 

That's my view:

```
<UIView top="safeAreaInsets.top" width="100%" height="headerHeight">
    <UILabel numberOfLines="2"
        left="16" top="16">
        My Title
    </UILabel>
</UIView>
<UIScrollView ...>...</UIScrollView```

When scroll I make the necessary calculations and update my header height using `setState(:animated:)` but this state change is causing some lags in my app.

How can I update the height state variable without affect the scroll animation? 

Thanks!

**Comment by nicklockwood** [comment]
@marciliojrs I suspect the problem is that calling setState is re-rendering everything, including the contents of the scrollview. Can you upload the project so I can debug it?

**Comment by marciliojrs** [comment]
@nicklockwood That's my suspect too, there's a way to avoid re-render everything? That's a client project so I cannot upload it but I'll try prepare a demo to show the problem.
